Polished counter Example - querying the Network ( NCTL and Testnet )
casper-network/docs-new pull request #135
Opened 2023-02-15 13:41 UTC by jonas089

Polished "querying the Network" in counter example ( NCTL and Testnet ). Added an example for the default configuration ( http://localhost:11101 and a link to peers on testnet.cspr.live to make the --node-address more clear.

2023-03-15 13:42 UTC, andrzej-casper commented
Rebased to new structure.

2023-03-16 08:45 UTC, andrzej-casper requested changes
I added 2 small suggestions.

2023-03-16 08:45 UTC, ghost commented on source/docs/casper/resources/tutorials/beginner/counter-testnet/commands.md
> +You can find a list of Testnet IP addresses [here](https://testnet.cspr.live/tools/peers)
```suggestion
You can find a list of Testnet IP addresses at [CSPR live](https://testnet.cspr.live/tools/peers).
```

2023-03-16 08:45 UTC, andrzej-casper commented on source/docs/casper/resources/tutorials/beginner/counter/commands.md
> +```
I like that you introduced example URL for this tutorial :+1: However, I would make it inline to keep bullet list concise:
```suggestion
-   The _node-address_ is the location of the RPC endpoint, which is typically represented in the form `http://IP:PORT`. In this particular tutorial, for a default-configured NCTL network running locally, the address you can use is `http://localhost:11101`.

2023-03-16 13:53 UTC, jonas089 commented
@andrzej-casper I committed your requested changes :) Thanks 👍🏻

2023-03-16 23:11 UTC, andrzej-casper approved these changes

2023-03-17 14:25 UTC, merged