178 check if rust can be added to sdks
casper-network/docs-new pull request #204
Opened 2023-04-13 16:00 UTC by jonas089

I added Rust examples utilising the casper-client crate alongside the Javascript and Python SDK examples. I tried to keep it simple and follow a similar structure. I tested all functions and everything looks good on my end.

2023-04-13 16:02 UTC, jonas089 commented
@melpadden @ACStoneCL @KMCreatesWorlds  it would be great if either of you could review my contribution. Thanks in advance :)

2023-04-18 19:57 UTC, KMCreatesWorlds requested changes
The general usage of the SDK is correct, only small suggestions to the comments etc. otherwise it looks good. After the commit of the suggestions it can be approved and merged.

2023-04-18 19:57 UTC, KMCreatesWorlds commented on source/docs/casper/developers/dapps/sdk/client-library-usage.md
> +use types and methods from casper_client:
```suggestion
Use types and methods from casper_client:
```

2023-04-18 19:57 UTC, KMCreatesWorlds commented on source/docs/casper/developers/dapps/sdk/client-library-usage.md
> +    // with session args:
```suggestion
    // Without session args:
    // let session_args: Vec<&str> = Vec::new();
    // With session args:
```

2023-04-18 19:57 UTC, KMCreatesWorlds commented on source/docs/casper/developers/dapps/sdk/client-library-usage.md
> +    // test with session args -> tbd
```suggestion
  
```

2023-04-19 13:46 UTC, KMCreatesWorlds approved these changes

2023-04-19 14:46 UTC, andrzej-casper approved these changes
I am giving approval, just to allow merge after Karol's review :rocket:  - he is great member of Tiger team, but since he does not belong to [Casper Association organization on GitHub](https://github.com/orgs/casper-network/teams), we cannot add him directly to [tiger-team](https://github.com/orgs/casper-network/teams/tiger-team/members) (code owner here).

2023-04-19 14:47 UTC, merged